name: mipripity_api
description: A simple backend for Mipripity.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.6.2
  yaml: ^3.1.2  # Added for parsing pubspec.yaml
  test: ^1.26.2

databases:
- name: mipripity_db
  databaseName: mipripity_app
  user: mipripity_user
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "15"